services:
  mysql:
    image: mysql:8.0
    container_name: mecaniqaqa-porto-velho-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mecaniqa_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - porto-velho-net

  redis:
    image: redis:alpine
    container_name: mecaniqaqa-porto-velho-redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - porto-velho-net

  api:
    build: .
    container_name: mecaniqaqa-porto-velho-api-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mecaniqa_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - porto-velho-net

volumes:
  mysql_data:
  redis_data:

networks:
  porto-velho-net:
    driver: bridge
